openapi: 3.0.3
info:
  title: Git Hub Profiles - OpenAPI 3.0
  description: >-
    Project used as a challenge in a selection process
  contact:
    email: joaofanchini@gmail.com
  version: 0.0.1
tags:
  - name: profile
    description: Related with information about Users profiles from Github
paths:
  /profile-info/{userProfile}:
    get:
      tags:
        - profile
      summary: Get information about a profile
      description: Get information about a profile by a username
      operationId: getProfileInfo
      parameters:
        - name: userProfile
          in: path
          description: User profile from Git Hub
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '400':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        '404':
          description: Info about user profile not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        '500':
          description: Unexpected exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'

components:
  schemas:
    ProfileResponse:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
          example: joaofanchini
        avatarUrl:
          type: string
          example: https://avatars.githubusercontent.com/u/31604369?v=4
        followers:
          type: array
          items:
            type: object
            properties:
              login:
                type: string
                example: login-user
              id:
                type: integer
                example: 123123
        repositories:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: repo
              id:
                type: integer
                example: 123123

    Fault:
      type: object
      properties:
        message:
          type: string
          example: Message
        exception:
          type: string
          example: ExceptionName
        cause:
          type: string
          example: Exception
        timestamp:
          type: integer
          format: int64